<a href="https://colab.research.google.com/github/BangAjus/Data-Analytics/blob/Data-Analysis/Wine_Quality.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv('WineQT.csv')
df

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,0
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5,1
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5,2
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,3
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1138,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6,1592
1139,6.8,0.620,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,9.5,6,1593
1140,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5,1594
1141,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6,1595
1142,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5,1597

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1143 entries, 0 to 1142
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         1143 non-null   float64
 1   volatile acidity      1143 non-null   float64
 2   citric acid           1143 non-null   float64
 3   residual sugar        1143 non-null   float64
 4   chlorides             1143 non-null   float64
 5   free sulfur dioxide   1143 non-null   float64
 6   total sulfur dioxide  1143 non-null   float64
 7   density               1143 non-null   float64
 8   pH                    1143 non-null   float64
 9   sulphates             1143 non-null   float64
 10  alcohol               1143 non-null   float64
 11  quality               1143 non-null   int64
 12  Id                    1143 non-null   int64
dtypes: float64(11), int64(2)
memory usage: 116.2 KB

In [ ]:
q = df['quality'].values
q = np.unique(q)
q

array([3, 4, 5, 6, 7, 8])

In [ ]:
am = df['quality'].value_counts().reset_index().sort_values(['index'])
am = [i for i in am['quality']]
am[1:]

[33, 483, 462, 143, 16]

In [ ]:
df['quality'].value_counts().reset_index().sort_values(['index'])

   index  quality
5      3        6
3      4       33
0      5      483
1      6      462
2      7      143
4      8       16

In [ ]:
df.corr()['quality'].sort_values(ascending=False)

quality                 1.000000
alcohol                 0.484866
sulphates               0.257710
citric acid             0.240821
fixed acidity           0.121970
Id                      0.069708
residual sugar          0.022002
pH                     -0.052453
free sulfur dioxide    -0.063260
chlorides              -0.124085
density                -0.175208
total sulfur dioxide   -0.183339
volatile acidity       -0.407394
Name: quality, dtype: float64

In [ ]:
test = df[df['quality'] == 3][-2:]
for i in range(4, 9):
    j = 1
    dfx = df[df['quality'] == i][-1*(am[j]//3):]
    test = pd.concat([test, dfx])
    j += 1    
nott = ['alcohol', 'sulphates', 'citric acid', 'fixed acidity', 'volatile acidity', 'total sulfur dioxide', 'quality']
for i in test.columns:
    if i not in nott:
        test = test.drop(columns=[i])
x_test = test.drop(columns=['quality'])
y_test = test[['quality']]

In [ ]:
train = df.copy()
col2 = ['alcohol', 'sulphates', 'citric acid', 'fixed acidity', 'volatile acidity', 'total sulfur dioxide', 'quality']
for i in train.columns:
    if i not in col2:
        train = train.drop(columns=[i])
x_train = train.drop(columns=['quality'])
y_train = train[['quality']]

In [ ]:
!pip install auto-sklearn

In [ ]:
from autosklearn.classification import AutoSklearnClassifier

In [ ]:
model = AutoSklearnClassifier(time_left_for_this_task=90)

In [ ]:
model.fit(x_train, y_train)

AutoSklearnClassifier(ensemble_class=<class 'autosklearn.ensembles.ensemble_selection.EnsembleSelection'>,
                      per_run_time_limit=9, time_left_for_this_task=90)

In [ ]:
model.leaderboard(detailed=True)

,rank,ensemble_weight,type,cost,duration,config_id,train_loss,seed,start_time,end_time,budget,status,data_preprocessors,feature_preprocessors,balancing_strategy,config_origin
model_id,,,,,,,,,,,,,,,,
4,1,0.14,random_forest,0.293651,2.406820,3,0.000000,0,1.676023e+09,1.676023e+09,0.0,StatusType.SUCCESS,[],[feature_agglomeration],none,Initial design
2,2,0.08,random_forest,0.309524,2.226520,1,0.000000,0,1.676023e+09,1.676023e+09,0.0,StatusType.SUCCESS,[],[no_preprocessing],none,Initial design
6,3,0.06,random_forest,0.322751,2.551273,5,0.003922,0,1.676023e+09,1.676023e+09,0.0,StatusType.SUCCESS,[],[feature_agglomeration],weighting,Initial design
3,4,0.02,random_forest,0.333333,2.708097,2,0.007843,0,1.676023e+09,1.676023e+09,0.0,StatusType.SUCCESS,[],[fast_ica],none,Initial design
11,5,0.02,random_forest,0.346561,7.647167,10,0.091503,0,1.676023e+09,1.676023e+09,0.0,StatusType.SUCCESS,[],[polynomial],none,Initial design
9,6,0.04,gradient_boosting,0.349206,1.597225,8,0.197386,0,1.676023e+09,1.676023e+09,0.0,StatusType.SUCCESS,[],[fast_ica],none,Initial design
13,7,0.02,random_forest,0.365079,2.118227,12,0.270588,0,1.676023e+09,1.676023e+09,0.0,StatusType.SUCCESS,[],[feature_agglomeration],none,Initial design
19,8,0.02,lda,0.399471,0.968928,18,0.398693,0,1.676023e+09,1.676023e+09,0.0,StatusType.SUCCESS,[],[polynomial],weighting,Initial design
15,9,0.28,adaboost,0.444444,2.650903,14,0.436601,0,1.676023e+09,1.676023e+09,0.0,StatusType.SUCCESS,[],[select_rates_classification],none,Initial design
8,10,0.04,liblinear_svc,0.468254,1.218894,7,0.439216,0,1.676023e+09,1.676023e+09,0.0,StatusType.SUCCESS,[],[polynomial],weighting,Initial design
5,11,0.08,gradient_boosting,0.484127,1.768971,4,0.352941,0,1.676023e+09,1.676023e+09,0.0,StatusType.SUCCESS,[],[no_preprocessing],weighting,Initial design
18,12,0.12,qda,0.510582,0.850958,17,0.501961,0,1.676023e+09,1.676023e+09,0.0,StatusType.SUCCESS,[],[no_preprocessing],none,Initial design
24,13,0.08,adaboost,0.695767,1.550061,23,0.683660,0,1.676023e+09,1.676023e+09,0.0,StatusType.SUCCESS,[],[fast_ica],weighting,Initial design

In [ ]:
model.score(x_test, y_test)

0.9122807017543859